apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      securityContext:
        runAsNonRoot: true

      containers:
        - name: angular-app
          image: angular-app:1.0.0
          ports:
            - containerPort: 80

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL