capabilities:
  secret_detection: false
  static_analysis: false
  dependency_analysis: false
  infrastructure_analysis: false
  build: true
  unit_testing: true
  integration_testing: false
  container_build: true
  container_scan: true
  sbom: true
  provenance: true
  policy_enforcement: true

build:
  working_directory: .
  runtime:
    language: node
    version: "22"
    package_manager: null
  command: null

testing:
  working_directory: .
  unit:
    enabled: false
    command: null
  integration:
    enabled: false
    command: null

container:
  dockerfile: ./Dockerfile
  context: .
  image:
    name: application
    tag: null
  registry:
    type: dockerhub
    repository: null
policy:
  paths: 
   - deploy/
  policy_paths: 
   - .devsecops/policies/security.rego