name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  security-pipeline:
    permissions:
      contents: read
      id-token: write

    uses: TasniimCh/Platform-Pipeline/.github/workflows/pipeline.yml@risk-advisor
    secrets:
      inherit 